### PR TITLE
Comms: SerialLink Threading Changes

### LINKED ISSUE #11849: Pixhawk Autoconnect Causes Extreme Lag
open failed "Permission error while locking the device" QSerialPort::PermissionError "CubePilot on ttyACM0 (AutoConnect)" autconnect: true
open failed "Permission error while locking the device" QSerialPort::PermissionError "CubePilot on ttyACM1 (AutoConnect)" autconnect: true

However connecting them manually does not cause this problem

### PR DESCRIPTION
**Pull request by HTRamsey**
Related to https://github.com/mavlink/qgroundcontrol/issues/11598
fixes #11849
The QThread inheritance will have to be removed after the remaining links are fixed
Tested by turning all streams to 100Hz and letting it run for a while:
image

### CODE REVIEW

File: src/Comms/LinkManager.cc [hunk 1]
```diff
@@ -257,11 +259,6 @@ void LinkManager::setConnectionsSuspended(QString reason)
     _connectionsSuspendedReason = reason;
 }
 
-void LinkManager::suspendConfigurationUpdates(bool suspend)
```
Comment (HTRamsey) [inline src/Comms/LinkManager.cc:260]: FYI this was never used anywhere and I don't see a significant need for it
