### PR TITLE
Vehicle: hide 'No GPS Lock' message if GPS is not present

### LINKED ISSUE #9380: "No Gps Lock for Vehicle" shows up on top of video even for GPS-less vehicles.
## Expected Behavior
Unobstructed video.

## Current Behavior
"No GPS Lock for Vehicle" shows at the center of the video

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
 - Connect a Pixhawk with ArduSub 4.0.2 flashed
 - Put the video in full screen in the fly view.

## System Information
When posting bug reports, include the following information
- Operating System: [e.g. iOS 12.1, Windows 8, macOS Mojave 10.14.1, Ubuntu 14]
- QGC Version:  4.1 and master
- QGC build: self-built from source
- Autopilot (with version): ArduSub 4.0.2

We could check if the vehicle has a GPS connected, or check if a GPS is crucial for this type of vehicle.
It would also be fine if this was displayed only over the map (as the map is not that useful without a GPS signal), but not over the video.

### PR DESCRIPTION
**Pull request by Williangalvani**
Fix #9380

With this, "No GPS Lock for Vehicle" will only show if the vehicle reports a GPS connected.

PX4 seems to always report a GPS. if there is none connected at boot, it's reported with an "error" status.
ArduPilot only reports a GPS after it is connected.

### CODE REVIEW

File: src/Vehicle/Vehicle.h [hunk 1]
```diff
@@ -554,6 +555,7 @@ class Vehicle : public FactGroup
     bool            readyToFly                  () { return _readyToFly; }
     bool            allSensorsHealthy           () { return _allSensorsHealthy; }
     QObject*        sysStatusSensorInfo         () { return &_sysStatusSensorInfo; }
+    bool            requiresGpsFix              () { return static_cast<bool>(_onboardControlSensorsPresent & SysStatusSensorGPS); }
```
Comment (patrickelectric) [inline src/Vehicle/Vehicle.h:558]: this function should be const.

Comment (patrickelectric) [inline src/Vehicle/Vehicle.h:558]: this function should be const

Comment (Williangalvani) [reply src/Vehicle/Vehicle.h]: right! fixed it.

**Comment by mrpollo** [comment]
thanks @Williangalvani

**Comment by Williangalvani** [comment]
Do you have a gps connected?

**Comment by atyshka** [comment]
No I don’t, the point is it’s indoors and I want to use vision_position_estimate messages instead of gps

**Comment by Williangalvani** [comment]
Then I guess the issue is that PX4 is sending the gps flag of the  `the onboard_control_sensors_present` flags of the `SYS_STATUS` message.
