### PR TITLE
Android: Update Serial Driver

### LINKED ISSUE #9052: I hope Android QGC can support CH340 module
Ch340 is usually used for USB to serial port, but currently The Android VERSION of QGC cannot connect the CH340 communication module via wired mode.
Now I have to forward the serial port data to TCP/UDP data through other software to connect with QGC, it's very inconvenient to use.

### LINKED ISSUE #10629: Add support for the wch ch34x serial port?
wch ch34x has an official Android driver, can you add it to the serial driver?

http://www.wch-ic.com/downloads/CH341SER_ANDROID_ZIP.html

### LINKED ISSUE #11007: Android: USB disconnect causes hang
Repro:
* Latest daily
* Connect cube back over usb
* Wait for connect to finish
* Pull USB plug
* QGC hangs

### LINKED ISSUE #11300: Android Serial Implementation
Implement the Android Serial functionality using the newer [usb-serial-for-android](https://github.com/mik3y/usb-serial-for-android) driver. Should allow compatibility with more devices and make it easier for custom builds to add compatibility with their devices. Will also allow removal of most of the custom QGC QSerialPort library for Android.

### LINKED ISSUE #11649: Serial COM-ports are not available on QGC Android
## Expected Behavior
If a device with Serial COM-ports is connected to Android device, then they should be available in QGC. 

## Current Behavior
When I connect a telemetry link or even Matek flight controller via USB their COM-ports are not available. Only when I plug in FTDI (UART to USB adapter) does QGC see COM-port, however, it is impossible to connect to it.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. Connect the Matek Flight controller (or any other) or Telemetry radio link to the Android tablet or smartphone.
2. Open QGC app > Application settings > COM links > Add > Select "Type: Serial"
3. Check the "Serial Port" drop-down option > It says "None Available"
4. Try to plug in another device/flight controller and repeat the steps from above > Same reaction

## System Information
- Operating System: Android 9, Android 13
- QGC Version: 4.4.0 x32/x64, 4.2.3.3 x32, 4.2.9 x64
- QGC build: Stable .apk
- Flight Controller: Matek H743, Telemetry Radio link with 2 COM-ports on USB Type-C

## Detailed Description
Why is this the bug of QGC? Well, Mission planner can recognize all COM-ports alright. When I plug in FTDI I'm able to connect as well. 
However, when I plugged in the following devices neither COM-ports was recognized by QGC:
1. Siyi mk32: QGC v4.2.3.3 х32;  QGC v4.4.0 х32, QGC v4.2.0 х32. Devices were connected via USB 2.0 and USB Type-C.
2. Nokia C32: QGC v4.4.0 х64 ; QGC v4.2.9 х64. Connected via USB Type-C.

### PR DESCRIPTION
**Pull request by HTRamsey**
Allows Android to work with most devices. Tested by updating firmware on a cube orange.
fixes #11300 
fixes #9052
closes #10629
fixes #11007
fixes #11649

### CODE REVIEW

File: android/src/org/mavlink/qgroundcontrol/QGCProber.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+{
+    static UsbSerialProber getQGCProber()
+    {
+        final ProbeTable customTable = new ProbeTable();
+
+        customTable.addProduct(QGCUsbId.VENDOR_PX4, QGCUsbId.DEVICE_PX4FMU_V1, CdcAcmSerialDriver.class);
+        customTable.addProduct(QGCUsbId.VENDOR_PX4, QGCUsbId.DEVICE_PX4FMU_V2, CdcAcmSerialDriver.class);
+        customTable.addProduct(QGCUsbId.VENDOR_PX4, QGCUsbId.DEVICE_PX4FMU_V3, CdcAcmSerialDriver.class);
+        customTable.addProduct(QGCUsbId.VENDOR_PX4, QGCUsbId.DEVICE_PX4FMU_V4, CdcAcmSerialDriver.class);
+        customTable.addProduct(QGCUsbId.VENDOR_PX4, QGCUsbId.DEVICE_PX4FMU_V4PRO, CdcAcmSerialDriver.class);
```
Comment (mrpollo) [inline android/src/org/mavlink/qgroundcontrol/QGCProber.java:19]: Do we need to add the whole list of FMU versions here?

File: android/src/org/mavlink/qgroundcontrol/QGCUsbId.java [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+    public static final int DEVICE_PX4FMU_V3 = 0x0011;
+    public static final int DEVICE_PX4FMU_V4 = 0x0012;
+    public static final int DEVICE_PX4FMU_V4PRO = 0x0013;
+    public static final int DEVICE_PX4FMU_V5 = 0x0032;
+    public static final int DEVICE_PX4FMU_V5X = 0x0033;
+    public static final int DEVICE_PX4FMU_V6C = 0x0038;
+    public static final int DEVICE_PX4FMU_V6U = 0x0036;
+    public static final int DEVICE_PX4FMU_V6X = 0x0035;
+    public static final int DEVICE_PX4FMU_V6XRT = 0x001D;
+    public static final int DEVICE_PX4MINDPX_V2 = 0x0030;
```
Comment (mrpollo) [inline android/src/org/mavlink/qgroundcontrol/QGCUsbId.java:51]: It seems like we already carry this information elsewhere, is there any way to avoid duplicating?

**Review by mrpollo — COMMENTED** [review]
Just have a question regarding duplicate hardware device information across the project

File: android/src/org/mavlink/qgroundcontrol/QGCProber.java (hunk 1 above)
Comment (HTRamsey) [reply android/src/org/mavlink/qgroundcontrol/QGCProber.java:19]: So this list (the entire custom table) is the only part I really have no idea about, as I can't test every device. The cube I used worked without the use of the customTable entirely. I honestly am not sure what to put in it or not.

File: android/src/org/mavlink/qgroundcontrol/QGCUsbId.java (hunk 2 above)
Comment (HTRamsey) [reply android/src/org/mavlink/qgroundcontrol/QGCUsbId.java:51]: USBBoardInfo.json, And I could probably come up with a way but I don't know Java well enough to do it easily. Maybe through CMake after we drop QMake.

**Comment by HTRamsey** [comment]
@DonLakeFlyer this may be useful for your herelink build

**Review by DonLakeFlyer — COMMENTED** [review]
For the places where we have duplicate info. Could you add a comment to both places to let people know they need to update both places not just one.

**Comment by HTRamsey** [comment]
At the moment the duplicate IDs defined in QGCUsbId.java aren't actually used so they don't need to update it. Those IDs are there to create a custom QGCProber.java but I am not sure if that will actually be necessary or not. We'll have to test some devices and find out. If it turns out it is actually needed, I can come back and somehow remove the need to define in both places
