### PR TITLE
Fix text overlay for recorded videos

### LINKED ISSUE #8766: Video overlay(subtitles) timestamps not consistent between samples
Issue raised by @gezzuzz here: https://github.com/mavlink/qgc-user-guide/pull/218#issuecomment-631667899

```
Dialogue: 0,0:00:09.9,0:00:10.9,Default,,0,0,0,,{\pos(10,35)}5/20/2020 1:59 PM
Dialogue: 0,0:00:11.0,0:00:12.0,Default,,0,0,0,,{\an3\pos(295,1075)}Depth:\NGround Speed:
```

This can cause flickering of the subtitles.

We should probably use the `end` of the last timestamp as start of the new one.

### PR DESCRIPTION
**Pull request by Williangalvani**
First commit fixes #8766 and the second updates the code to work with the new values widget.

### CODE REVIEW

File: src/VideoManager/SubtitleWriter.h [hunk 1]
```diff
@@ -35,15 +35,18 @@ class SubtitleWriter : public QObject
...
 
 private slots:
     // Captures a snapshot of telemetry data from vehicle into the subtitles file.
     void _captureTelemetry();
 
 private:
     QTimer _timer;
-    QStringList _values;
-    QDateTime _startTime;
+    QList<FactPath> _values;
```
Comment (jaxxzer) [inline src/VideoManager/SubtitleWriter.h:49]: rename this to _facts, we get the fact values after building this list

File: src/VideoManager/SubtitleWriter.cc [hunk 2]
```diff
@@ -102,10 +122,18 @@ void SubtitleWriter::_captureTelemetry()
...
 
     // Make a list of "factname:" strings and other with the values, so one can be aligned left and the other right
-    for (const auto& i : _values) {
-        valuesStrings << QStringLiteral("%2 %3").arg(vehicle->getFact(i)->cookedValueString())
-                                                .arg(vehicle->getFact(i)->cookedUnits());
-        namesStrings << QStringLiteral("%1:").arg(vehicle->getFact(i)->shortDescription());
+    for (const FactPath& fact : _values) {
+        //Vehicle facts
+        if(fact.groupName == vehicleFactGroupName || fact.groupName == ""){
+            valuesStrings << QStringLiteral("%2 %3").arg(vehicle->getFact(fact.factName)->cookedValueString())
```
Comment (jaxxzer) [inline src/VideoManager/SubtitleWriter.cc:128]: Are facts without groups ever allowed?

File: src/VideoManager/SubtitleWriter.cc [hunk 3]
```diff
@@ -22,6 +22,8 @@
 #include <QDate>
 
 QGC_LOGGING_CATEGORY(SubtitleWriterLog, "SubtitleWriterLog")
+QString vehicleFactGroupName = "Vehicle";
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:25]: const, QStringLiteral

File: src/VideoManager/SubtitleWriter.cc [hunk 4]
```diff
@@ -22,6 +22,8 @@
...
+QStringList settingsSources = {"ValuePageUserSettings2", "ValuePageDefaultSettings2"};
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:26]: const, QStringLiteral, you can also use initializer-list

File: src/VideoManager/SubtitleWriter.cc [hunk 5]
```diff
@@ -33,13 +35,35 @@ SubtitleWriter::SubtitleWriter(QObject* parent)
...
+    _facts.clear();
+
+    // check user settings first, use default if user settings are empty
+    for (const QString& settingsGroup : settingsSources) {
+        QSettings settings;
+        settings.beginGroup(settingsGroup);
+        const int nRows = settings.value("rows/size").toInt();
+        // iterate through all rows and columns saving the facts into _facts
+        for(int row = 1; row < nRows + 1; row++) {
+            int nColumns = settings.value(QString("rows/%1/columns/size").arg(row)).toInt();
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:51]: Maybe you should check if the toInt calls are working and settings.value got a non invalid qvariant and print an warning message, failing in silence is terrible to debug.

File: src/VideoManager/SubtitleWriter.cc [hunk 6]
```diff
@@ -33,13 +35,35 @@ SubtitleWriter::SubtitleWriter(QObject* parent)
 
 void SubtitleWriter::startCapturingTelemetry(const QString& videoFile)
 {
-    // Get the facts displayed in the values widget and capture them, removing the "Vehicle." prefix.
-    QSettings settings;
-    settings.beginGroup("ValuesWidget");
-    _values = settings.value("large").toStringList().replaceInStrings(QStringLiteral("Vehicle."), QString());
-    _values += settings.value("small").toStringList().replaceInStrings(QStringLiteral("Vehicle."), QString());
+    QString factNameTemplate = QStringLiteral("rows/%1/columns/%2/factName");
+    QString groupNameTemplate = QStringLiteral("rows/%1/columns/%2/groupName");
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:39]: const

File: src/VideoManager/SubtitleWriter.cc [hunk 7]
```diff
@@ -101,22 +125,31 @@ void SubtitleWriter::_captureTelemetry()
     QStringList valuesStrings;
 
     // Make a list of "factname:" strings and other with the values, so one can be aligned left and the other right
-    for (const auto& i : _values) {
-        valuesStrings << QStringLiteral("%2 %3").arg(vehicle->getFact(i)->cookedValueString())
-                                                .arg(vehicle->getFact(i)->cookedUnits());
-        namesStrings << QStringLiteral("%1:").arg(vehicle->getFact(i)->shortDescription());
+    for (const FactPath& fact : _facts) {
+        //Vehicle facts
+        if(fact.groupName == vehicleFactGroupName || fact.groupName == ""){
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:130]: fact.groupName.isEmpty()

File: src/VideoManager/SubtitleWriter.cc (hunk 5 above)
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:51]: QStringLiteral

File: src/VideoManager/SubtitleWriter.cc [hunk 8]
```diff
@@ -101,22 +125,31 @@ void SubtitleWriter::_captureTelemetry()
...
+            valuesStrings << QStringLiteral("%2 %3").arg(vehicle->getFact(fact.factName)->cookedValueString())
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:131]: Maybe having a helper variable for `auto factData = vehicle->getFact(fact.factName)` to help with the readability of the code ?
You can also change this variable for groupName and remove all the code inside the if/else to be common and only changing the factData

File: src/VideoManager/SubtitleWriter.cc [hunk 9]
```diff
@@ -33,13 +35,35 @@ SubtitleWriter::SubtitleWriter(QObject* parent)
...
+        settings.beginGroup(settingsGroup);
+        const int nRows = settings.value("rows/size").toInt();
+        // iterate through all rows and columns saving the facts into _facts
+        for(int row = 1; row < nRows + 1; row++) {
+            int nColumns = settings.value(QString("rows/%1/columns/size").arg(row)).toInt();
+            for(int column = 1; column < nColumns + 1; column++) {
+                QString factGroupName = settings.value(groupNameTemplate.arg(row).arg(column)).toString();
+                QString factName = settings.value(factNameTemplate.arg(row).arg(column)).toString();
+                FactPath path {factGroupName, factName};
+                _facts += path;
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:56]: You can also do `_facts += FactPath{factGroupName, factName}`

**Comment by DonLakeFlyer** [comment]
Is this good to merge?

**Comment by Williangalvani** [comment]
Sorry, I missed your message. This should be ready in the next week or so, just needs a little more testing.

File: src/VideoManager/SubtitleWriter.cc [hunk 10]
```diff
@@ -22,6 +22,15 @@
...
 QGC_LOGGING_CATEGORY(SubtitleWriterLog, "SubtitleWriterLog")
+const QString vehicleFactGroupName = QStringLiteral("Vehicle");
+
+QStringList settingsSources{
+    QStringLiteral("ValuePageUserSettings2"),
+    QStringLiteral("ValuePageDefaultSettings2")
+};
+
+const QString factNameTemplate = QStringLiteral("rows/%1/columns/%2/factName");
+const QString groupNameTemplate = QStringLiteral("rows/%1/columns/%2/groupName");
```
Comment (patrickelectric) [inline src/VideoManager/SubtitleWriter.cc:33]: can't this variables be in the class and not global ? or why not inside the function scope ?

Comment (Williangalvani) [reply src/VideoManager/SubtitleWriter.cc:33]: yes, I just haven't tested and pushed the changes yet.

File: src/VideoManager/SubtitleWriter.cc [hunk 11]
```diff
@@ -22,6 +22,15 @@
 #include <QDate>
 
 QGC_LOGGING_CATEGORY(SubtitleWriterLog, "SubtitleWriterLog")
+const QString SubtitleWriter::vehicleFactGroupName = QStringLiteral("Vehicle");
+
+const QStringList SubtitleWriter::settingsSources = QStringList{
+    QStringLiteral("TelemetryBarUserSettingsWIP02-0"),
```
Comment (Williangalvani) [inline src/VideoManager/SubtitleWriter.cc:28]: Hi @DonLakeFlyer

I noticed this needed some more changes to handle the new instruments widget, but I have some questions:

Are [these](https://github.com/mavlink/qgroundcontrol/blob/master/src/QmlControls/HorizontalFactValueGrid.cc#L17) still WIP?

I can't figure out where the `-0` and `-2` came from... Culd you point me in the right direction?
Thanks!

Comment (DonLakeFlyer) [reply src/VideoManager/SubtitleWriter.cc:28]: The WIP should be removed from these settings names, since they are no longer WIP. That said you shouldn't be reading these settings directly. With the current code what you want to do can't really be done. It requires some refactoring of HorizontalFactValueGrid and FactValueGrid. Is this a new feature or something that was working before you are now trying to get working again?

Comment (Williangalvani) [reply src/VideoManager/SubtitleWriter.cc:28]: I was trying to fix #8766, but I realized that the new implementation broke it, so I'm trying to fix that too.

The behavior in 4.0 is that it reads all the items from the values widgets and uses them for the [video overlay](https://docs.qgroundcontrol.com/master/en/FlyView/VideoOverlay.html).

I'll take a good look at HorizontalFactValueGrid and FactValueGrid tomorrow.

Comment (DonLakeFlyer) [reply src/VideoManager/SubtitleWriter.cc:28]: > The behavior in 4.0 is that it reads all the items from the values widgets and uses them for the [video overlay](https://docs.qgroundcontrol.com/master/en/FlyView/VideoOverlay.html).

Ah, crap. Ok, let me clean up a couple things and then you should be able to create a standalone HorizontalFactValueGrid and read from it.

**Comment by DonLakeFlyer** [comment]
After latest changes:
* Create a FactValueGrid with null parent
* Set userSettingsGroup/defaultSettingsGroup to the HorizontalFactValueGroup values
* Call _loadSettings
* Read what you need from FactValueGrid
* Destroy FactValueGrid

**Comment by Williangalvani** [comment]
> After latest changes:
> 
> * Create a FactValueGrid with null parent
> * Set userSettingsGroup/defaultSettingsGroup to the HorizontalFactValueGroup values
> * Call _loadSettings
> * Read what you need from FactValueGrid
> * Destroy FactValueGrid

Great, thank you!

**Comment by LorenzMeier** [comment]
This is pending on the current release feedback.

**Comment by DonLakeFlyer** [comment]
@Williangalvani This is ready to go right?

**Comment by Williangalvani** [comment]
> @Williangalvani This is ready to go right?

yes!
