### PR TITLE
Select language fixes

### LINKED ISSUE #11541: The interface language does not match the selected language
## Expected Behavior
When choosing a language, see the corresponding translation of the interface.

## Current Behavior
For example: when choosing Chinese, Azeibarjan is displayed, etc.

## Steps to Reproduce:
1. Open QGroundControl Daily
2. Change `Application Settings` -> `General` -> `General` -> `Language` to Chinese.

## System Information
When posting bug reports, include the following information
- Operating System: KDE Neon 6.0 (Wayland) based on Ubuntu 22.04
- QGC Version: master:02da1496 2024-04-11 11:08:57 -0700 64 bit
- QGC build: daily (Appimage)
- Flight Controller: Any
- Autopilot (with version): Any

## Detailed Description
Nothing to add.

## Log Files and Screenshots

<details>
  <summary>QGC Console Logs</summary>
  
```
[I] at :0 - "Could not load the Qt platform plugin "wayland" in "" even though it was found."
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:261 - "Settings location "/home/user/.config/QGroundControl.org/QGroundControl Daily.ini" Is writable?: true"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/Utilities/QGCLoggingCategory.cc:122 - "Filter rules "*Log.debug=false\nGStreamerAPILog.debug=true\nqt.qml.connections=false""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at :0 - "Couldn't load VAAPI library"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/Vehicle/MAVLinkLogManager.cc:360 - "MAVLink logs directory: "/home/user/other/Documents/QGroundControl Daily/Logs""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QtLocationPlugin/QGCMapEngine.cpp:157 - "Map Cache in: "/home/user/.cache/QGCMapCache300" / "qgcMapCache.db""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/VideoReceiver/GstVideoReceiver.cc:285 - "Stop called on empty URI"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/VideoReceiver/GstVideoReceiver.cc:285 - "Stop called on empty URI"
[E] at qrc:/qml/MainRootWindow.qml:289 - "qrc:/qml/MainRootWindow.qml:289:21: QML ColumnLayout: Binding loop detected for property "height""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "az_AZ" is not present"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "az_AZ" is not present"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "zh_CN" is not present"
[E] at :0 - "QString::arg: Argument missing: "项目 1" , 0"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "zh_CN" is not present"
[E] at :0 - "QString::arg: Argument missing: "项目 1" , 0"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "asa_TZ" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "asa_TZ""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "asa_TZ""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "az_AZ" is not present"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "bn_BD" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "bn_BD""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "bn_BD""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "bas_CM" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "bas_CM""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "bas_CM""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "bem_ZM" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "bem_ZM""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "bem_ZM""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "bez_TZ" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "bez_TZ""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "bez_TZ""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "bs_BA" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "bs_BA""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "bs_BA""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "br_FR" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "br_FR""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "br_FR""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "ca_ES" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "ca_ES""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "ca_ES""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "zh_CN" is not present"
[E] at :0 - "QString::arg: Argument missing: "项目 1" , 0"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "cu_RU" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "cu_RU""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "cu_RU""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "hr_HR" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "hr_HR""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "hr_HR""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "fr_FR" is not present"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "gl_ES" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "gl_ES""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "gl_ES""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "lg_UG" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "lg_UG""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "lg_UG""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "el_GR" is not present"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "smn_FI" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "smn_FI""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "smn_FI""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "ia_001" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "ia_001""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "ia_001""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "kab_DZ" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "kab_DZ""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "kab_DZ""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "ia_001" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "ia_001""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "ia_001""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "kab_DZ" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "kab_DZ""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "kab_DZ""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "az_AZ" is not present"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "cu_RU" is not present"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:383 - "Error loading source localization for "cu_RU""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:388 - "Error loading json localization for "cu_RU""
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:378 - "Qt lib localization for "az_AZ" is not present"
[D] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QGCApplication.cc:353 - "System reported locale: QLocale(English, Latin, United States) ; Name "en_US" ; Preffered (used in maps):  "en""
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QtLocationPlugin/QGCMapUrlEngine.cpp:151 - "getProviderTypeFromQtMapId : map id not found: -1"
[E] at /home/runner/work/qgroundcontrol/qgroundcontrol/src/QtLocationPlugin/QGCMapUrlEngine.cpp:151 - "getProviderTypeFromQtMapId : map id not found: -1"
[E] at qrc:/qt-project.org/imports/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml:37 - "qrc:/qt-project.org/imports/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml:37:5: QML Dialog: Binding loop detected for property "implicitWidth""
[E] at qrc:/qt-project.org/imports/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml:37 - "qrc:/qt-project.org/imports/QtQuick/Dialogs/quickimpl/qml/FileDialog.qml:37:5: QML Dialog: Binding loop detected for property "implicitWidth""
```
</details>

[Screencast_20240516_115524.webm](https://github.com/mavlink/qgroundcontrol/assets/15276371/c719a55f-c039-4330-b34b-6215acc660d6)

### PR DESCRIPTION
**Pull request by DonLakeFlyer**
There were multiple problem here all star6ing from the fact the we had QLocale::Language ids stored in a json file. This is now set up in code such so that things don't get screwed up. Also added much more validation along the way that the right things are happening.

While testing this I discovered a number of problems with the Chinese json translations where the enum commands which changed to a Chinese char. Hence the string split for them was failing. Luckily most had already been fixed up in Crowdin and I just approved them And then fixed the missing ones.

Closes  #11541

### CODE REVIEW

File: src/Settings/AppSettings.cc [hunk 1]
```diff
@@ -192,33 +216,39 @@ DECLARE_SETTINGSFACT_NO_FUNC(AppSettings, qLocaleLanguage)
         FactMetaData*   metaData            = _qLocaleLanguageFact->metaData();
         QStringList     rgOriginalStrings   = metaData->enumStrings();
```
Comment (HTRamsey) [inline src/Settings/AppSettings.cc:217]: I guess the original values aren't needed anymore, unless you want to check for changes

Comment (DonLakeFlyer) [reply src/Settings/AppSettings.cc:217]: Oops, correct. Those are gone now from the json.

**Review by HTRamsey — APPROVED** [review]
